### ISSUE TITLE
作者看完请删掉

### ISSUE THREAD

**Issue by sunxiuming92** [MiYogurt/nodelover-books#2]
看了作者写的ts，真的是用心在写了，很容易理解，对于入门的人来说，很棒（暂时看到第二章，没遇到问题，作者请删掉下）

**Comment by sunxiuming92** [comment]
建议作者 可以在掘金上推广，流量比较大

**Comment by MiYogurt** [comment]
这辈子最讨厌就是推广了，有的东西强求不来。以前在掘金发过几次，总是被拒就再也没法了，就当遇见了是缘分好了，没遇见是明。

同时非常感谢各位的肯定。
