### ISSUE TITLE
‘Symbol 与模块 7.md’ 发现一处语病

### ISSUE THREAD

**Issue by anarckk** [MiYogurt/nodelover-books#3]
![qq 20190117103426](https://user-images.githubusercontent.com/27038948/51291830-8a7ba200-1a43-11e9-8872-a549bb5db5f6.png)

**Comment by MiYogurt** [comment]
感谢指正。

**Comment by anarckk** [comment]
恩，不客气，很喜欢 node_lover 的开源书籍。
